apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pingapp.fullname" . }}-config
  labels:
    {{- include "pingapp.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  PORT: {{ .Values.config.port | quote }}
  ENABLE_CHAOS: {{ ternary "1" "0" .Values.chaos.enabled | quote }}
